<link rel="stylesheet" href="<?= $wwwUrl ?>/css/frere.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/style.css">

<header>
  <div "nav-bar--deux">
  <a><i class="fas fa-calendar-minus bar--deux"></i></a>

  <div id="liens">
  <i class="fas fa-link"></i>
  <div class="nav--list hide">
  <a href="https://www.facebook.com/parasitesanss/" target="_blank">Facebook</a>
  <a href="https://www.youtube.com/channel/UCYPvwTee8RJ1pp0IYibegUQ/videos" target="_blank">Youtube</a>
  </div>

  </div>
</div>
</header>

<section>
<div class="div--frere">
  <div class="presentation--un">
  <img class="un" src="<?= $wwwUrl ?>/images/frere/img4.jpg" alt="photo">
  <img src="<?= $wwwUrl ?>/images/frere/img2.jpg" alt="photo">
</div>
<div class="presentation">
  <img class="un" src="<?= $wwwUrl ?>/images/frere/img3.jpg" alt="photo">
  <img class="un" src="<?= $wwwUrl ?>/images/frere/img1.jpg" alt="photo">
 </div>
 <h1 class="nom"><span class="nom--span">frere de sac 4tet<span></h1>
  <p class="p--pop"><span class="underline">Présentation du groupe :</span><br>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  <div class="video">
  <iframe width="560" height="315" src="https://www.youtube.com/embed/LWb8EJllr80" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  <iframe width="560" height="315" src="https://www.youtube.com/embed/lE9OYQO7CfM" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  </div>

</div>
  <div class="header--slider">
    <button class="prec"><i class="fas fa-arrow-left"></i></button>

  <div class="your-class">
  <div><img src="<?= $wwwUrl ?>/images/frere/1.jpg" alt="photo"></div>
  <div><img src="<?= $wwwUrl ?>/images/frere/2.jpg" alt="photo"></div>
  <div><img src="<?= $wwwUrl ?>/images/frere/3.jpg" alt="photo"></div>
  <div><img src="<?= $wwwUrl ?>/images/frere/4.jpg" alt="photo"></div>
  <div><img src="<?= $wwwUrl ?>/images/frere/5.jpg" alt="photo"></div>
  <div><img src="<?= $wwwUrl ?>/images/frere/6.jpg" alt="photo"></div>
  <div><img src="<?= $wwwUrl ?>/images/frere/8.jpg" alt="photo"></div>
</div>
<button class="next"><i class="fas fa-arrow-right"></i></button>
</div>

</section>
