<link rel="stylesheet" href="<?= $wwwUrl ?>/css/style.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/frere.css">

<section>
<h1 class="nom"><span class="nom--span">frere de sac 4tet<span></h1>
<div class="div--frere">
  <img class="img" src="<?= $wwwUrl ?>/images/frere/img4.jpg" alt="photo Marie">
  <img class="img deux" src="<?= $wwwUrl ?>/images/frere/img2.jpg" alt="photo Jean-loup">
  <img class="img" src="<?= $wwwUrl ?>/images/frere/img1.jpg" alt="photo femme">
  <img class="img trois" src="<?= $wwwUrl ?>/images/frere/img3.jpg" alt="photo homme">
 </div>

  <p class="p--pop"><span class="underline title--concert">Présentation du groupe :</span>
  <br>
  De la Renaissance française à la transe suédoise, les chemins de traverse des musiques traditionnelles européennes, arpentés par un combo familial au son unique. Timbres oubliés et palette d'arrangements entre puissance et impressionnisme, sont les cartes à jouer de ce corps musical aux 4 membres tour à tour solistes, harmonistes et rythmiciens.
  Avec la complicité du public danseur ou auditeur, s'ouvre un nouveau chapitre du livre de cette fratrie, qui marie la connaissance de la tradition aux audaces du néo-trad.
  Frères de Sac 4tet nous emmène ainsi, sur un tapis sonore généreux, à la recherche d'un folk européen d'aujourd'hui.
  « L'homme, quand il cesse de dormir, est avant tout le jouet de sa mémoire. » (André Breton).</p>
</div>

    <div class="div--articles">
      <p class="frere--para"><span class="artistes">Marie Mazille<br>Nyckelharpa, clarinettes, voix, componium</span>
      <br>
      Diplômée du Conservatoire en violon et clarinette (1993) et du CFMI (1995), elle s'oriente vers la musique traditionnelle avec le groupe Tsirba (musiques de l'Est) puis fonde en 1996 Kordévan, ensemble néo-trad grenoblois (3 albums), pour lequel elle compose pendant 10 ans.
      Arrangeuse et accompagnatrice en chanson française (Gérard Pierron, Henri
      Courseaux, Isabelle Bazin, Laurent Berger...), elle compose régulièrement pour le théâtre (Apethi-Philippe Pujol, Trio Mineur-Thierry Tochon, Théâtre du Grabuge-Géraldine Béni- chou...) et la danse contemporaine (tournée en Afrique avec la Cie DIT-Robert Seyfried). Egalement clown-musicienne.
      S'accomplit en particulier dans les projets participatifs en prenant la direction artistique du projet In Situ : 3 ans d'expériences remarquées dans le quartier de la Villeneuve (Grenoble), de multiples déclinaisons (concerts, expositions, happenings, double CD...), en résidence d'artistes à Annemasse (74) jusqu'en 2021.
      Aujourd'hui sur scène avec Cordofonic (quatuor à cordes d'Auvergne), Etsaut trio (spectacle « De la terre dans l'canon »), et bien sûr Frères de Sac 4tet.</p>
      <p class="frere--para"><span class="artistes">Marie Mercier<br>Clarinette basse, clarinette</span>
      <br>
      A initialement mené un parcours musical dans le milieu de la musique classique et a obtenu un Master en pédagogie instrumentale à la Haute Ecole de Musique de Genève dans la classe de Romain Guyot en 2016. Elle a de plus reçu, à l’issue de ses études, la bourse culturelle de la Fondation Leenaards.
      Recherchant l’éclectisme au fil des rencontres, elle navigue dans divers domaines musicaux : Frères de Sac 4tet nourrit son désir de faire danser et de faire vivre un répertoire aux racines ancestrales ; le groupe Parasite Sans S lui permet d’exploser ses propres frontières avec deux complices (Anna Benzakoun et Alexandra Bellon) dans des jeux d’improvisations aux reliefs hirsutes et d’inspiration lunaire ; le groupe Meigmata (Laurent Sourisse et Michael Chapon) la fait naviguer à travers des influences balkanes-jazz dans des compositions originales aux rythmiques impaires et asymétriques ; en tant qu’interprète de musique contemporaine, elle joue régulièrement avec l’Ensemble Contrechamps et collabore avec de jeunes compositeurs du bassin genevois.
      </p>
      <p class="frere--para"><span class="artistes">Christophe Sacchettini <br>Flûtes à bec, cornemuse du Centre, cromorne </span>
      <br>
      Flûtiste à bec de formation baroque, il tombe très tôt dans la marmite bouillonnante du folk franco-européen (prodigieux réservoir de matières, d’images et d’énergie), qu'il cherche à concilier avec son instrument, emmenant la flûte à bec vers des territoires rarement atteints.
      Il est co-fondateur du collectif grenoblois MusTraDem dont il assume aujourd’hui la co-direction artistique (avec ses complices de toujours Stéphane Milleret et Norbert Pignol) puis du CPMDT (Collectif des Professionnels des Musiques et Danses Traditionnelles, 2003), enfin directeur artistique des Nuits du Folk de l’Adaep-Aremdat (1993 à 2005) où se développe le néo-bal trad.
      Musicien de scène tous azimuts, improvisateur, pédagogue (les stages Mydriase depuis 1992), il se promène aujourd’hui avec le groupe Djal, la chanteuse Natacha Ezdra, en duo avec Norbert Pignol (concert et e- bal)...et bien sûr Frères de Sac 4tet, évolution actuelle d'un duo de 20 ans. Il collabore avec metteurs en scène, chorégraphes, cinéastes, chanteurs, conteurs ou écrivains. Partage son temps entre projets « grand public », milieu « trad », bizarreries expérimentales, et collectage urbain (projet In Situ).
      S’intéresse en particulier aux racines imaginaires, à l’élaboration sociale des fictions de la mémoire.
      </p>
      <p class="frere--para"><span class="artistes">Jean-Loup Sacchettini<br>Accordéons diatoniques, compositions </span>
      <br>
      Formé à l'accordéon diatonique auprès de Norbert Pignol et Stéphane Milleret, il éclot dans le creuset des bals hebdomadaires Adaep / MusTraDem des années 1990.
      Il se spécialise au début comme musicien de bal, notamment en collaborant de- puis 1993 avec Geneviève Chuzel, maître en danses traditionnelles, pour ses stages et ateliers.
      Egalement compositeur, il écrit une importante partie du répertoire du duo Frères de Sac qu'il fonde en 1998 et qui multiplie tournées et collaborations en se faisant une place à part dans le paysage des « nouvelles musiques traditionnelles » franco-européennes.
      Pédagogue et militant de l'accès à la musique pour tous, il enseigne aujourd'hui au Conservatoire de Bourgoin-Jallieu (38), et au sein de l'équipe Mydriase (depuis 1994).
      De nombreuses influences (dont les musiques modales et les musiques répétitives, aux liens intimes avec la musique traditionnelle) ont cristallisé son goût pour l'évidence, la note qui sonne, la mélodie qui marque et l'harmonie qui décale, que ce soit pour ses compositions, pour des reprises traditionnelles ou de compositeurs actuels.
      </p>
    </div>

    <div class="try">
    <div class="sound">
      <h2 class="title--concert gros">Listen to our music</h2>
      <iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/514556007&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe>
    </div>

    <div class="upcoming">
     <h2 class="title--concert gros">Upcoming dates</h2>
      <?php if (empty($events) == false) { ?>
    <table class="table tableau">
      <thead class="hide">
      <tr class="table">
        <td>Concerts</td>
        <td>Date</td>
        <td>Heure</td>
        <td>adresse</td>
        <td>Infos</td>
      </tr>
      </thead>
      <tbody>
      <?php foreach($events as $event) { ?>
          <tr  class="table">
          <td><?=$event['event']?></td>
          <td class="date"><?=$event['date']?></td>
          <td class="heure"><?=$event['heure']?></td>
          <td><?=$event['adresse']?><?=$event['zip']?></td>
        </tr>
          <?php } ?>
    </tbody>
    </table>
    <?php } ?>
        </div>
      </div>

  <div class="video">
  <iframe class="meig--videos" width="460" height="315" src="https://www.youtube.com/embed/LWb8EJllr80" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen target="_blank"></iframe>
  <iframe  class="meig--videos" width="460" height="315" src="https://www.youtube.com/embed/lE9OYQO7CfM" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen target="_blank"></iframe>
  </div>

  <div class="header--slider">
    <button class="prec"><i class="fas fa-arrow-left"></i></button>

  <div class="your-class">
  <div><img src="<?= $wwwUrl ?>/images/frere/1.jpg" alt="photo"></div>
  <div><img src="<?= $wwwUrl ?>/images/frere/2.jpg" alt="photo"></div>
  <div><img src="<?= $wwwUrl ?>/images/frere/3.jpg" alt="photo"></div>
  <div><img src="<?= $wwwUrl ?>/images/frere/4.jpg" alt="photo"></div>
  <div><img src="<?= $wwwUrl ?>/images/frere/5.jpg" alt="photo"></div>
  <div><img src="<?= $wwwUrl ?>/images/frere/6.jpg" alt="photo"></div>
  <div><img src="<?= $wwwUrl ?>/images/frere/8.jpg" alt="photo"></div>
</div>
<button class="next"><i class="fas fa-arrow-right"></i></button>
</div>

<div class="icones--div">
  <p class="us">Follow us</p>
  <a href="https://www.facebook.com/Fr%C3%A8res-de-Sac-4tet-196996980822686/" target="_blank"><i class="fab fa-facebook icone1"></i></a>
  <a href="https://www.youtube.com/results?search_query=frere+de+sac+4tet" target="_blank"><i class="fab fa-youtube icone2"></i></a>
</div>

</section>
