<link rel="stylesheet" href="<?= $wwwUrl ?>/css/style.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/accueil.css">

<div id="accueil--div" class="contain">

  <div class="div--groupe">
  <div><h1 class="title--parasite">Parasite sans S</h1></diV>
  <a href="<?= $requestUrl ?>/accueil/parasite?id=1">
    <img class="home--img-cinq" src="<?= $wwwUrl ?>/images/musique/5.jpg"  alt="parasite sans s"></a>
  </div>

  <div class="div--groupe">
  <div><h1 class="title--pop">L'ID-POP</h1></div>
  <a href="<?= $requestUrl ?>/accueil/pop?id=2">
    <img class="home--img-six" src="<?= $wwwUrl ?>/images/musique/6.jpeg"  alt="L'Id Pop"></a>
  </div>

  <div class="div--groupe">
  <div><h1 class="title--meigmata">Trio Meigmata</h1></div>
  <a href="<?= $requestUrl ?>/accueil/meigmata?id=3">
    <img class="home--img-sept" src="<?= $wwwUrl ?>/images/musique/7.jpg"  alt="Meigmata"></a>
  </div>

  <div class="div--groupe">
  <div><h1 class="title--frere">Frères de Sac 4tet</h1></div>
  <a href="<?= $requestUrl ?>/accueil/frere?id=4">
    <img class="home--img-huit" src="<?= $wwwUrl ?>/images/musique/8.jpg"  alt="frere de sac 4tet"></a>
  </div>

</div>
