<link rel="stylesheet" href="<?= $wwwUrl ?>/css/accueil.css">

<div id="accueil--div">

  <a href="<?= $requestUrl ?>/accueil/parasite">
    <h1 class="title--parasite">Parasite sans S</h1>
    <img class="home--img-cinq" src="<?= $wwwUrl ?>/images/musique/5.jpg"  alt="parasite sans s"></a>
    <a href="<?= $requestUrl ?>/accueil/pop">
      <h1 class="title--pop">L'ID-POP</h1>
      <img class="home--img-six" src="<?= $wwwUrl ?>/images/musique/6.jpeg"  alt="L'Id Pop"></a>



      <a href="<?= $requestUrl ?>/accueil/meigmata">
      <h1 class="title--meigmata">Trio Meigmata</h1>
      <img class="home--img-sept" src="<?= $wwwUrl ?>/images/musique/7.jpg"  alt="Meigmata"></a>
      <a href="<?= $requestUrl ?>/accueil/frere">
      <h1 class="title--frere">Frères de Sac 4tet</h1>
      <img class="home--img-huit" src="<?= $wwwUrl ?>/images/musique/8.jpg"  alt="frere de sac 4tet"></a>


    </div>
