<link rel="stylesheet" type="text/css" href="<?= $wwwUrl ?>/css/style.css">
<link rel="stylesheet" type="text/css" href="<?= $wwwUrl ?>/css/parasite.css">

<section>
  <div class="div--parasite">
    <img class="title--img" src="<?= $wwwUrl ?>/images/parasite/para.jpg" alt="titre">

    <img class="img-neuf" src="<?= $wwwUrl ?>/images/musique/9.jpg"  alt="parasite sans s">
    <p class="p--parasite"><span class="underline title--concert underline">Présentation du groupe :</span>
      <br>
      La musique improvisée de PARASITE SANS S trace la cartographie des émotions. Elle se veut lunaire, mais triomphante, entre le bourdon et les plumes, tantôt elle fait peur, tantôt elle rassure, mais jamais elle ne suit un tracé balisé. Sciemment elle cherche les broussailles électriques et les pas qui déraillent. Ses atmosphères chamaniques se perdent avec délice dans des expérimentations qui recyclent les traditions ancestrales sous l'œil de la chimère.
      <br>Naturellement les choses se croisent un pied dans le passé, l’autre dans le présent et le troisième dans l’ultra-futur.</p>
      <img class="groupe--img" src="<?= $wwwUrl ?>/images/parasite/groupe.jpg" alt="photo">
    </div>

    <div class="div--para">
      <p class="p--para"><span class="artistes">Alexandra Bellon<br>PARASITE DE L’ULTRA-FUTUR</span>
        <br>
        Transformée par le choc de l’effervescence du rythme, Alexandra Bellon débute naturellement les percussions et la batterie dès son plus jeune âge. Elle se forme au sein de structures musicales classiques sans pour autant s’éloigner du lien organique qui la lie à ses instruments. Elle obtient un Bachelor de percussions et deux Master à la HEM de Genève, pédagogie musicale (2013) puis interprétation (2015), tout en poursuivant ses recherches personnelles : goût pour l’expérimentation et pratique de l’improvisation, attraction pour la transe et les musiques répétitives, curiosité insatiable à destination des arts vivants. Dans un premier temps, elle explore le milieu des orchestres symphoniques, aventure qui la mène dans de grandes formations européennes (orchestre du festival Verbier, de la suisse romande, de Liège, de Lorraine...) mais très vite elle donne à son parcours une trajectoire plus personnelle.
      </p>
      <p class="p--para"><span class="artistes">Anna Benzakoun<br>PARASITE DU PRÉSENT</span>
      <br>
      Musicienne de formation classique. Née de parents musiciens elle commence le piano à l’âge de cinq ans et obtient un Master de Concertiste ainsi qu’un Master de Pédagogie après avoir étudié dans les prestigieux Conservatoire Royal de Bruxelles et Haute École de Musique de Genève.
      Forte de cette base classique Anna se laisse guider par sa soif de diversité, source de richesse. Elle se rend en Inde durant l’été 2014 pour y étudier la Musique Indienne et l’esraj avec Pandit Barun Kumar Pal à New Delhi. Ce même été elle propose à Marie Mercier et Alexandra Bellon de former un groupe, lieu de recherche artistique et de création commune où elle trouvera peu à peu sa place à la voix et au synthétiseur : Parasite sans « S ». Compositions originales, improvisations libres, projets pluridisciplinaires, ce groupe difficile à catégoriser interroge, séduit, gratte, pique.. mais ne laisse pas indifférent.
      </p>
      <p class="p--para"><span class="artistes">Marie Mercier<br>PARASITE DU PASSÉ</span>
      <br>
      Clarinettiste, a commencé un parcours musical exclusivement mené dans le milieu de la musique classique. Inspirée par de grands maîtres comme Bruno Martinez, Florent Héau et Romain Guyot, elle ponctue cette période de formation par l’obtention d’un Master of Arts en pédagogie instrumentale à la Haute Ecole de Musique de Genève. Son activité musicale genevoise s’est tout d’abord développée au sein de divers ensembles tels que l’Ensemble Contrechamps et l’ensemble Vidya.
      Attirée par la collaboration avec le département de composition de la HEM de Genève, Marie Mercier a développé son esthétique autour de la musique contemporaine et expérimentale et a accru ses possibilités instrumentales à travers la clarinette basse et la clarinette contrebasse bénéficiant des conseils de David Poissonnier, Alain Billard, Luis Naon, Pascal Dusapin, Philippe Manoury, Philippe Albéra, et Alexandre Babel.
      Ceci enclencha un virage musical stimulé par le besoin de s’imprégner d’autres domaines artistiques ainsi que diverses approches musicales. Les rencontres découlant de cette démarche furent décisives.
      </p>
    </div>

<div class="try">
<div class="sound">
  <h2 class="title--concert gros">Listen to our music</h2>
  <iframe class="frame-sound" width="40%" height="200" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/99957536&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe>
</div>

<div class="upcoming">
  <h2 class="title--concert gros">Upcoming dates</h2>
  <?php if (empty($events) == false) { ?>
<table class="table tableau">
  <thead class="hide">
  <tr class="table">
    <td>Concerts</td>
    <td>Date</td>
    <td>Heure</td>
    <td>adresse</td>
    <td>Infos</td>
  </tr>
  <thead>
  <tbody>
  <?php foreach($events as $event) { ?>
      <tr class="table">
      <td><?=$event['event']?></td>
      <td class="date"><?=$event['date']?></td>
      <td class="heure"><?=$event['heure']?></td>
      <td><?=$event['adresse']?><?=$event['zip']?></td>
    </tr>
      <?php } ?>
  </tbody>
</table>
<?php } ?>
    </div>
  </div>

    <div class="header--slider">
      <button class="prec"><i class="fas fa-arrow-left"></i></button>

      <div class="your-class responsive">
        <div><img src="<?= $wwwUrl ?>/images/parasite/douze.jpg" alt="photo" width="354" height="246"></div>
        <div><img src="<?= $wwwUrl ?>/images/parasite/quatre.jpg" alt="photo" width="354" height="246"></div>
        <div><img src="<?= $wwwUrl ?>/images/parasite/six.jpg" alt="photo" width="354" height="246"></div>
        <div><img src="<?= $wwwUrl ?>/images/parasite/trois.jpg" alt="photo" width="354" height="246"></div>
        <div><img src="<?= $wwwUrl ?>/images/parasite/treize.jpg" alt="photo" width="354" height="246"></div>
        <div><img src="<?= $wwwUrl ?>/images/parasite/deux.jpg" alt="photo"></div>
        <div><img src="<?= $wwwUrl ?>/images/parasite/huit.jpg" alt="photo"></div>
        <div><img src="<?= $wwwUrl ?>/images/parasite/quatorze.jpg" alt="photo"></div>
        <div><img src="<?= $wwwUrl ?>/images/parasite/sept.jpg" alt="photo"></div>
        <div><img src="<?= $wwwUrl ?>/images/parasite/quinze.jpg" alt="photo"></div>
        <div><img src="<?= $wwwUrl ?>/images/parasite/seize.jpg" alt="photo"></div>
        <div><img src="<?= $wwwUrl ?>/images/parasite/one.jpg" alt="photo"></div>
        <div><img src="<?= $wwwUrl ?>/images/parasite/two.jpg" alt="photo"></div>
        <div><img src="<?= $wwwUrl ?>/images/parasite/three.jpg" alt="photo"></div>
        <div><img src="<?= $wwwUrl ?>/images/parasite/four.jpg" alt="photo"></div>
        <div><img class="five" src="<?= $wwwUrl ?>/images/parasite/five.jpg" alt="photo"></div>
      </div>
      <button class="next"><i class="fas fa-arrow-right"></i></button>
    </div>

    <div class="icones--div">
      <p class="us">Follow us</p>
      <a href="https://www.facebook.com/parasitesanss/" target="_blank"><i class="fab fa-facebook icone1"></i></a>
      <a href="https://www.youtube.com/channel/UCYPvwTee8RJ1pp0IYibegUQ/videos" target="_blank"><i class="fab fa-youtube icone2"></i></a>
    </div>

  </section>
