<header>
  <nav class="nav-bar container">
    <div class="nav-list1">
      <a class="" href="<?= $requestUrl ?>/accueil"><i class="fas fa-home"></i></a>
    </div>

    <div class="nav-bar--deux">
      <a><i class="fas fa-calendar-minus bar--deux"></i></a>

      <div id="liens" class="bar--deux">
        <i class="fas fa-link"></i>
        <div class="nav--list hide">
          <a href="https://www.facebook.com/parasitesanss/" target="_blank">Facebook</a>
          <a href="https://www.youtube.com/channel/UCYPvwTee8RJ1pp0IYibegUQ/videos" target="_blank">Youtube</a>
        </div>

      </div>
    </div>

    <div id="user--connect">
      <i class="fas fa-user user bar--deux"></i>
      <div class="under-nav-list hide">

        <?php if (array_key_exists('user', $_SESSION)){ ?>

          <a href="<?= $requestUrl ?>/user/profil">Mon Profil</a>

          <?php if($_SESSION['user']['role'] == 'admin') {?>

            <a class="" href="<?= $requestUrl ?>/admin">Admin</a>

          <?php } ?>

          <a class="" href="<?= $requestUrl ?>/user/logout">Déconnexion</a>

        <?php } else {?>
          <div id="opa" class="nav--hide position">
            <a class="" href="<?= $requestUrl ?>/user/login">Connexion</a>
            <a class="" href="<?= $requestUrl ?>/user/register">S'enregistrer</a>
          </div>

        </div>
      <?php } ?>

    </div>
  </nav>
</header>
