<link rel="stylesheet" href="<?= $wwwUrl ?>/css/style.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/pop.css">

<section>
<div class="div--pop">
  <img class="logo" src="<?= $wwwUrl ?>/images/l'id-pop/black.jpg" alt="logo">
  <img class="title--id" src="<?= $wwwUrl ?>/images/l'id-pop/21_Fotor.png" alt="photo">

  <div class="para--pop">
  <p class="p--pop"><span class="underline title--concert">Présentation du groupe :</span><br>
    <br>
    L’Id Pop, un trio incongru issu de trois rencontres fortes. Chansons originales pop-rock avec une touche électro-folk, le groupe
    voyage à travers des leads enflammés de guitare électrique, la douceur
    de l’acoustique, des riffs rock, une grande liberté d’improvisation, des
    mélismes orientalisants, de l’intime à la déflagration d’énergie sauvage.
    <br>
    « Lentement des fissures se forment sur des doctrines scellées par le
    temps »
    « Sans détournement je préfère un esprit libre aux idées imposées »
    « On est des souffleurs de vers, de poèmes, de ceux qui se répandent sur
    ta peau, indélébiles, mais tellement loyaux »</p>
    <p class="p--pop">
      <ul>
        <li>Paroles, musique, arrangements : Id Pop</li>
        <li>Sea-line : Voix, Boîte à rythme</li>
        <li>Sergio Barbieri : Guitares</li>
        <li>Marie Mercier : Clarinette, Clarinette basse</li>
      </ul>
  </p>
  </div>

    <div class="upcoming">
      <h2 class="title--concert">Upcoming dates</h2>
      <?php if (empty($events) == false) { ?>
    <table class="table tableau">
      <thead class="hide">
      <tr class="table">
        <td>Concerts</td>
        <td>Date</td>
        <td>Heure</td>
        <td>adresse</td>
        <td>Infos</td>
      </tr>
    </thead>
     <tbody>
      <?php foreach($events as $event) { ?>
          <tr class="table">
          <td><?=$event['event']?></td>
          <td class="date"><?=date("d-m-Y",strtotime($event['date']))?></td>
          <td class="heure"><?=$event['heure']?></td>
          <td><?=$event['adresse']?><?=$event['zip']?></td>
          <td class="heure"><?=$event['infos']?></td>
        </tr>
          <?php } ?>
     </tbody>
    </table>
    <?php } ?>
        </div>

</div>

  <div class="header--slider">
    <button class="prec"><i class="fas fa-arrow-left"></i></button>

  <div class="your-class">
  <div><img src="<?= $wwwUrl ?>/images/l'id-pop/22_Fotor.png" alt="photo"></div>
  <div><img src="<?= $wwwUrl ?>/images/l'id-pop/8_Fotor.png" alt="photo"></div>
  <div><img src="<?= $wwwUrl ?>/images/l'id-pop/10_Fotor.png" alt="photo"></div>
  <div><img src="<?= $wwwUrl ?>/images/l'id-pop/12_Fotor.png" alt="photo"></div>
  <div><img src="<?= $wwwUrl ?>/images/l'id-pop/14_Fotor.png" alt="photo"></div>
  <div><img src="<?= $wwwUrl ?>/images/l'id-pop/16_Fotor.png" alt="photo"></div>
  <div><img src="<?= $wwwUrl ?>/images/l'id-pop/5_Fotor.png" alt="photo"></div>
  <div><img src="<?= $wwwUrl ?>/images/l'id-pop/24_Fotor.png" alt="photo"></div>
  <div><img src="<?= $wwwUrl ?>/images/l'id-pop/25.png" alt="photo"></div>

</div>
<button class="next"><i class="fas fa-arrow-right"></i></button>
</div>

<div class="icones--div">
  <p class="us">Follow us</p>
  <a href="https://www.facebook.com/marie.mercier.5076" target="_blank"><i class="fab fa-facebook icone1"></i></a>
</div>

</section>
