<link rel="stylesheet" href="<?= $wwwUrl ?>/css/pop.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/style.css">

<section>

<div class="div--pop">

  <h1 class="title--h1">l'ID-POP</h1>
  <img class="img--2" src="<?= $wwwUrl ?>/images/l'id-pop/5.png" alt="photo">
  <img class="title--pop" src="<?= $wwwUrl ?>/images/l'id-pop/21_Fotor.png" alt="photo">
  <p class="p--pop">Présentation du groupe :<br>
    <br>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

</div>

  <div class="header--slider">
    <button class="prec"><i class="fas fa-arrow-left"></i></button>

  <div class="your-class">
  <div><img src="<?= $wwwUrl ?>/images/l'id-pop/22_Fotor.png" alt="photo"></div>
  <div><img src="<?= $wwwUrl ?>/images/l'id-pop/8_Fotor.png" alt="photo"></div>
  <div><img src="<?= $wwwUrl ?>/images/l'id-pop/10_Fotor.png" alt="photo"></div>
  <div><img src="<?= $wwwUrl ?>/images/l'id-pop/12_Fotor.png" alt="photo"></div>
  <div><img src="<?= $wwwUrl ?>/images/l'id-pop/14_Fotor.png" alt="photo"></div>
  <div><img src="<?= $wwwUrl ?>/images/l'id-pop/16_Fotor.png" alt="photo"></div>
  <div><img src="<?= $wwwUrl ?>/images/l'id-pop/5_Fotor.png" alt="photo"></div>
  <div><img src="<?= $wwwUrl ?>/images/l'id-pop/24_Fotor.png" alt="photo"></div>
  <div><img src="<?= $wwwUrl ?>/images/l'id-pop/25.png" alt="photo"></div>

</div>
<button class="next"><i class="fas fa-arrow-right"></i></button>
</div>

</section>
