<link rel="stylesheet" href="<?= $wwwUrl ?>/css/pop.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/style.css">

<header>
  <div id="liens" class="bar--deux">
    <div class="nav--list hide">
      <a class="texte" href="https://www.facebook.com/parasitesanss/" target="_blank">Facebook</a>
      <a class="texte" href="https://www.youtube.com/channel/UCYPvwTee8RJ1pp0IYibegUQ/videos" target="_blank">Youtube</a>
    </div>

  </div>
</header>

<section>
<div class="div--pop">
  <h1 class="title--h1">l'ID-POP</h1>
  <img class="img--2" src="<?= $wwwUrl ?>/images/l'id-pop/5.png" alt="photo">
  <img class="title--id" src="<?= $wwwUrl ?>/images/l'id-pop/21_Fotor.png" alt="photo">
  <p class="p--pop"><span class="underline title--concert">Présentation du groupe :</span><br>
    <br>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

    <div>
      <h2 class="title--concert">Concerts à venir</h2>
      <?php if (empty($events) == false) { ?>
    <table class="table">
      <tr class="table">
        <td>Concerts</td>
        <td>Date</td>
        <td>Heure</td>
        <td>adresse</td>
        <td>Infos</td>
      </tr>
      <?php foreach($events as $event) { ?>
          <tr class="table">
          <td><?=$event['event']?></td>
          <td><?=$event['date']?></td>
          <td><?=$event['heure']?></td>
          <td><?=$event['adresse']?><?=$event['zip']?></td>
          <td><?=$event['infos']?></td>
        </tr>
          <?php } ?>
    </table>
    <?php } ?>
        </div>

</div>

  <div class="header--slider">
    <button class="prec"><i class="fas fa-arrow-left"></i></button>

  <div class="your-class">
  <div><img src="<?= $wwwUrl ?>/images/l'id-pop/22_Fotor.png" alt="photo"></div>
  <div><img src="<?= $wwwUrl ?>/images/l'id-pop/8_Fotor.png" alt="photo"></div>
  <div><img src="<?= $wwwUrl ?>/images/l'id-pop/10_Fotor.png" alt="photo"></div>
  <div><img src="<?= $wwwUrl ?>/images/l'id-pop/12_Fotor.png" alt="photo"></div>
  <div><img src="<?= $wwwUrl ?>/images/l'id-pop/14_Fotor.png" alt="photo"></div>
  <div><img src="<?= $wwwUrl ?>/images/l'id-pop/16_Fotor.png" alt="photo"></div>
  <div><img src="<?= $wwwUrl ?>/images/l'id-pop/5_Fotor.png" alt="photo"></div>
  <div><img src="<?= $wwwUrl ?>/images/l'id-pop/24_Fotor.png" alt="photo"></div>
  <div><img src="<?= $wwwUrl ?>/images/l'id-pop/25.png" alt="photo"></div>

</div>
<button class="next"><i class="fas fa-arrow-right"></i></button>
</div>

</section>
