<!-- Message de notification -->

<!-- Code HTML à écrire -->
  <link rel="stylesheet" href="<?= $wwwUrl ?>/css/home.css">

      <main class="home--main">
        <div>
        <a href="<?= $requestUrl ?>/accueil">
            <img class="home--img-un" src="<?= $wwwUrl ?>/images/musique/1.jpg"  alt="Marie Mercier">
        </a>
        <h1 class="home--title">Marie Mercier</h1>

        <div class="home--container">
        <a href="<?= $requestUrl ?>/accueil">
            <img class="home--img-deux" src="<?= $wwwUrl ?>/images/musique/2.jpg"  alt="Marie Mercier">
        </a>
        <a href="<?= $requestUrl ?>/accueil">
            <img class="home--img-trois" src="<?= $wwwUrl ?>/images/musique/3.jpg"  alt="Marie Mercier">
        </a>
        <a href="<?= $requestUrl ?>/accueil">
            <img class="home--img-quatre" src="<?= $wwwUrl ?>/images/musique/4.jpg"  alt="Marie Mercier">
        </a>
        </div>

      </div>
    </main>
