<link rel="stylesheet" href="<?= $wwwUrl ?>/css/accueil.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/conservatoire.css">

<section id="page--conserv">

  <div class="img-cons">
    <img class="img--float" src="<?= $wwwUrl ?>/images/musique/img-marie.jpg" alt="marie">
    <img class="img--float" src="<?= $wwwUrl ?>/images/musique/img-marie-2.jpg" alt="marie">
    <img class="img--float" src="<?= $wwwUrl ?>/images/musique/img-marie-3.jpg" alt="marie">
  </div>

  <div class="para--conservatoire">
    <article class="art--conserv">
      <img class="img--logo" src="<?= $wwwUrl ?>/images/musique/logo.jpeg" alt="logo">
      <h1 class="gras title--marie">Marie Mercier</h1>
      <p><h2 class="gras">Enseignement de la clarinette et clarinette basse :</h2><br>
        <ul>
          <li>Les mardis et mercredis au centre de Thônex-Villa - 9A avenue de Tronchet - 1226 Thônex</li>
          <li>Les mardis et jeudi au Centre des Pâquis-Musique - 34bis rue du Môle - 1201 Genève</li>
        </ul>
        <a href="https://cpmdt.ch/programme/vents-2/clarinette/" target="_blank">Programme</a></p>
      </article>

      <article class="art--conserv">
        <p><h2 class="gras">Ensemble Junior</h2><br>
          Enseignement collectif pour les jeunes musiciens dès la première année de pratique jusqu’à la 4ème. Collaboration avec Antoinette Baehler (Basson) et Yves Massy (Trombone).<br>
          « Vous jouez d’un instrument à vent ? Venez jouer en groupe dès les premiers mois de pratique ! Apprentissage par oralité, improvisations, jeux.»<br>
          <br>
          <a href="https://courscomplementaires.ch/recherche/?k=ensemble+junior" target="_blank">Cours complémentaires</a><br>
          <h4>Représentations :</h4>
          <ul>
            <li>Portes ouvertes CPMDT - Samedi 21 Mars</li>
            <li>Portes ouvertes CMG - Vendredi 3 Avril</li>
            <li>Fête de la Musique - 20-21 Juin</li>
          </ul>
        </p>
      </article>

      <article class="art--conserv">
        <p><h2 class="gras">Ensemble Création :</h2><br>
          L’atelier Création vous propose de monter un ciné-concert-spectacle de A à Z à jouer dans et hors les murs du Conservatoire populaire. Une année pour créer, mettre en scène et confronter nos disciplines (musique, danse, théâtre) à la vidéo (film à trou, slow motion,…) pour un moment d’expression à partager. <br>
          <a href="https://courscomplementaires.ch/recherche/?k=ensemble+cr%C3%A9ation" target="_blank"></a><br>
          <h4>Représentations :</h4>
          <ul>
            <li>Mercredi 3 juin - GDA - CPMDT rue d'Ivernois, 7</li>
            <li>6-7 Juin - Festival Court Circuit - Lausanne</li>
          </ul>
        </p>
      </article>

      <article class="art--conserv">
        <p><h2 class="gras">Autres projets en cours :</h2><br>
          Atelier Musique de Bal en collaboration avec les classes de Sihem-Laura Thomasson (Flûte) et Elodie Redon (Guitare)
          <h4>Dates de prestations :</h4>
          <ul>
            <li>Samedi 21 Mars - Portes Ouvertes - Vieille Ville, Genève</li>
            <li>Mercredi 1er avril - Audition de Centre - Point Favre, Chêne-Bourg</li>
          </ul>
        </p>
      </article>

      <article class="art--conserv">
        <p><h2 class="gras">Saison Mosaïque :</h2><br>
          Avec le groupe Mεigmaτa
          <h4>Ateliers Samedi 25 Avril avec Marie Mercier et Michael Chapon :</h4>
          <ul>
            <li>Initiation à l’improvisation modale</li>
            <li>Initiation aux pédales d’effets</li>
            <li>Introduction aux mesures composées</li>
            <li>Les mesures impaires à la batterie</li>
          </ul>
          Concert avec participation des élèves Vendredi 19 Juin 19h
        </p>
      </article>
    </div>

    <div class="dates">
      <div class="upcoming">
        <h2 class="title--concert gros">Upcoming dates</h2>
        <?php if (empty($events) == false) { ?>
          <table class="table tableau">
            <thead class="hide">
              <tr class="table">
                <td>Concerts</td>
                <td>Date</td>
                <td>Heure</td>
                <td>adresse</td>
                <td>Infos</td>
              </tr>
            </thead>
            <tbody>
              <?php foreach($events as $event) { ?>
                <tr  class="table">
                  <td><?=$event['event']?></td>
                  <td class="date"><?=date("d-m-Y",strtotime($event['date']))?></td>
                  <td class="heure"><?=$event['heure']?></td>
                  <td><?=$event['adresse']?><?=$event['zip']?></td>
                  <td class="heure"><?=$event['infos']?></td>
                <?php } ?>
              </tbody>
            </table>
          <?php } ?>
        </div>
      </div>

      <div class="icones--div">
        <p class="us">Follow us</p>
        <a href="https://www.facebook.com/conservatoirepopulaire.ch" target="_blank"><i class="fab fa-facebook icone1"></i></a>
      </div>

    </section>
