<link rel="stylesheet" href="<?= $wwwUrl ?>/css/style.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/profil.css">

<div>
  <h3 class="title--profil">Mon profil</h3>

  <form class="b-form" action="<?=$requestUrl ?>/user/profil" method="POST">
    <input class="input" type="text" name="firstname" placeholder="Prénom" value="<?=$user['firstname']?>">
    <input class="input" type="text" name="lastname" placeholder="Nom" value="<?=$user['lastname']?>">
    <input class="input" type="text" name="email" placeholder="Email" value="<?=$user['email']?>">

    <select class="button" name="nomgroupe" placeholder="Nom du groupe">
         <?php foreach ($groupes as $groupe) { ?>
           <?php if($user['groupe_id'] === $groupe['groupeid']) {?>
             <option selected value="<?= $groupe['groupeid'] ?>"><?= $groupe['nomgroupe'] ?></option>
           <?php }else {?>
             <option value="<?= $groupe['groupeid'] ?>"><?= $groupe['nomgroupe'] ?></option>
           <?php }?>
         <?php } ?>
    </select>

    <input class="submit" type="submit" value="Modifier">
  </form>

</div>
