<link rel="stylesheet" href="<?= $wwwUrl ?>/css/style.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/admin.css">

<h1 class="title--admin">Admin</h1>
<hr>
<div class="container">
  <h2 class="title--admin gestion">Gestion des groupes</h2>
  <a class="add" href="<?=$requestUrl ?>/admin/add"><i class="fas fa-plus-circle"></i> Ajouter un nouveau groupe</a>
<table class="table">
  <tr>
    <td>Photo</td>
    <td>Nom</td>
    <td>Action</td>
  </tr>

  <?php foreach ($groupes as $groupe) { ?>
    <tr>
      <td><img src="<?= $wwwUrl ?>/images/groupe/<?=$groupe['photo']?>"></td>
      <td><?=$groupe['nomgroupe']?></td>
      <td>
          <a class="modif" href="<?=$requestUrl ?>/admin/update?id=<?=$groupe['groupeid']?>"><i class="fas fa-pen"></i></a>
					<a class="modif" href="<?=$requestUrl ?>/admin/delete?id=<?=$groupe['groupeid']?>"><i class="fas fa-trash-alt"></i></a>
      </td>
    </tr>
  <?php } ?>
  </table>

<div id="form--admin">
  <form  class="table--form parasite-form" action="<?=$requestUrl?>/admin/addevent" method="POST">
    <h2>Calendrier</h2>
    <input type="text" name="event" placeholder="Evènement">
    <select class="button" id="nomgroupe" name="nomgroupe">
      <?php foreach ($groupes as $groupe) { ?>
        <option value="<?= $groupe['groupeid'] ?>"><?= $groupe['nomgroupe'] ?></option>
      <?php } ?>
   </select>
    <input type="date" name="date" placeholder="Date">
    <input type="time" name="heure" placeholder="Heure">
    <input type="text" name="adresse" placeholder="Adresse">
    <input type="text" name="zip" placeholder="Code postal">
    <input type="text" name="infos" placeholder="informations">
    <input class="button" type="submit" value="Valider">
  </form>
</div>

<div>
  <h2 class="title--admin gestion">Gestion du calendrier</h2>
  <table class="table">
    <tr>
      <td>Event</td>
      <td>Date</td>
      <td>Heure</td>
      <td>Adresse</td>

      <td></td>
    </tr>
     <?php foreach($allshows as $allshow) { ?>
        <tr>
        <td><?=$allshow['event']?></td>
        <td><?=$allshow['date']?></td>
        <td><?=$allshow['heure']?></td>
        <td><?=$allshow['adresse']?></td>
      

        <td><a class="add" href="<?=$requestUrl ?>/user/delete?id=<?=$allshow['Id']?>"><i class="fas fa-trash-alt"></i></a></td>
      </tr>
        <?php } ?>
  </table>
</div>

 <hr/>
 <h2 class="title--register">Gestion des musiciens</h2>
 <div class="register">
 	<h3>Nouveau musicien</h3>
 	<form class="b-form" action="<?=$requestUrl?>/admin/register" method="POST">
        <select class="button" id="nomgroupe" name="nomgroupe">
          <?php foreach ($groupes as $groupe) { ?>
            <option value="<?= $groupe['groupeid'] ?>"><?= $groupe['nomgroupe'] ?></option>
          <?php } ?>
       </select>
     <input type="text" name="firstname" placeholder="Prénom">
 		<input type="text" name="lastname" placeholder="Nom">
 		<input type="text" name="email" placeholder="Email">
 		<input type="text" name="password" placeholder="Mot de passe">
 		<input class="button-register" type="submit" value="Enregister">
 	</form>
 </div>
 <table class="table">
   <tr>
     <td>Nom</td>
     <td>Prénom</td>
     <td>Email</td>
     <td></td>
   </tr>
    <?php foreach($musiciens as $musicien) { ?>
       <?php if($musicien['email'] !== $_SESSION['user']['email']) { ?>
       <tr>
       <td><?=$musicien['firstname']?></td>
       <td><?=$musicien['lastname']?></td>
       <td><?=$musicien['email']?></td>
       <td><a class="add" href="<?=$requestUrl ?>/user/delete?id=<?=$musicien['Id']?>"><i class="fas fa-trash-alt"></i></a></td>
     </tr>
       <?php } ?>
       <?php } ?>
 </table>
</div>
