<link rel="stylesheet" href="<?= $wwwUrl ?>/css/meigmata.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/style.css">

<header>
  <div id="liens" class="bar--deux">
    <div class="nav--list hide">
      <a class="texte" href="https://www.facebook.com/Trio-M%CE%B5%E1%BD%B7gma%CF%84a-235810870668756/?ref=bookmarks" target="_blank">Facebook</a>
      <a class="texte" href="https://www.youtube.com/channel/UCbYvtSG39TLtFSE2dBx9eAA" target="_blank">Youtube</a>
    </div>

  </div>
</header>

<section>

<div class="div--meigmata">
  <div class="essai">
  <img class="title--M" src="<?= $wwwUrl ?>/images/meigmata/nom.png" alt="photo">
  <h1 class="title--h1"><strong>Trio Meigmata</strong></h1>
  <img class="img--meigmata" src="<?= $wwwUrl ?>/images/meigmata/groupe.jpg" alt="photo">
 </div>
  <p class="p--pop"><span class="underline">Présentation du groupe :</span><br>
    <br>
    Dans les sinuosités structurelles entre compositions originales et improvisations, le groupe Mείgmaτa explore les combinaisons asymétriques fortement influencées par les musiques balkanes, jazz et contemporaines. Entre savoureuses voluptés, mélodies mélismatiques et énergie sauvage, le trio mitonne une étonnante cuisine de raffinements sonores.</p>

    <div class="div--meig">
      <p class="meig--para"><span class="artistes">Laurent Sourisse<br>Clavier</span>
        <br>
      Pratiquant l'improvisation au piano sous plusieurs formes (classique, jazz...), avec curiosité et un goût des belles harmonies et des rythmiques riches issu de sa formation (écriture, piano, percussions), Laurent Sourisse enseigne à la Haute Ecole de Musique de Genève depuis 2009, notamment dans les filières de pédagogie, et à l'Institut Jaques-Dalcroze depuis 2001.
      </p>
      <p class="meig--para"><span class="artistes">Marie Mercier<br>Clarinettes, Basse électrique</span>
      <br>
      Musicienne éclectique et passionnée par la création provoquée par les rencontres, Marie Mercier navigue dans des univers musicaux divers avec Parasite Sans S (improvisation libre), Frères de Sac 4tet (Néo-Trad), L’Id-Pop (Chanson Pop-Rock), Vidya (Musique Contemporaine) et Container GVA (Musique Contemporaine). Elle enseigne également la clarinette à au Conservatoire Populaire de Genève.
      </p>
      <p class="meig--para"><span class="artistes">Michael Chapon<br>Batterie DU PASSÉ</span>
      <br>
      Après des études de percussion classique à la HEM de Genève, Michael Chapon se concentre sur la batterie qu'il étudie à la Los Angeles Music Academy où il se familiarise avec tous styles de musiques actuelles. Son intérêt pour les rythmes de l'Inde ainsi que sa passion pour la danse Flamenca orientent son travail à la batterie vers les musiques à mesures composées, ou encore vers l'accompagnement de danse contemporaine. Il enseigne la batterie au Conservatoire Populaire de Musique de Genève ainsi qu'à l'Institut de Percussion du Pays de Gex.
      </p>
    </div>

  <div class="video">
  <iframe class="meig--videos" width="460" height="315" src="https://www.youtube.com/embed/mPexrSD1_Lg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen target="_blank"></iframe>
  <iframe class="meig--videos" width="460" height="315" src="https://www.youtube.com/embed/UOR0oeGQRrc" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen target="_blank"></iframe>
  </div>

</div>
  <div class="header--slider">
    <button class="prec"><i class="fas fa-arrow-left"></i></button>

  <div class="your-class">
  <div><img src="<?= $wwwUrl ?>/images/meigmata/batteur.jpg" alt="photo"></div>
  <div><img src="<?= $wwwUrl ?>/images/meigmata/marie.jpg" alt="photo"></div>
  <div><img src="<?= $wwwUrl ?>/images/meigmata/pianiste.jpg" alt="photo"></div>
</div>
<button class="next"><i class="fas fa-arrow-right"></i></button>
</div>

</section>
