<link rel="stylesheet" href="<?= $wwwUrl ?>/css/accueil.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/login.css">

<div>
  <img class="title--M" src="<?= $wwwUrl ?>/images/musique/15.jpg" alt="photo">
</div>

<div class="register">
	<h3 class="title--register">Mot de passe oublié</h3>
	<form class="b-form" action="<?=$requestUrl?>/user/passwordreset" method="POST">
    <input type="hidden" name="token" value="<?= $token ?>">
		<input type="password" name="password" placeholder="Nouveau mot de passe">
		<input type="password" name="passconfirm" placeholder="Vérification">
		<input class="button-register" type="submit" value="Enregister">
	</form>
</div>
